<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    public function run()
    {   
        $languages = [
            ['language_name' => 'Afrikaans', 'language_code' => 'af', 'language_name_vi' => 'Tiếng Afrikaans'],
            ['language_name' => 'Albanian', 'language_code' => 'sq', 'language_name_vi' => 'Tiếng Albania'],
            ['language_name' => 'Amharic', 'language_code' => 'am', 'language_name_vi' => 'Tiếng Amhara'],
            ['language_name' => 'Arabic', 'language_code' => 'ar', 'language_name_vi' => 'Tiếng Ả Rập'],
            ['language_name' => 'Armenian', 'language_code' => 'hy', 'language_name_vi' => 'Tiếng Armenia'],
            ['language_name' => 'Azerbaijani', 'language_code' => 'az', 'language_name_vi' => 'Tiếng Azerbaijan'],
            ['language_name' => 'Basque', 'language_code' => 'eu', 'language_name_vi' => 'Tiếng Basque'],
            ['language_name' => 'Belarusian', 'language_code' => 'be', 'language_name_vi' => 'Tiếng Belarus'],
            ['language_name' => 'Bengali', 'language_code' => 'bn', 'language_name_vi' => 'Tiếng Bengal'],
            ['language_name' => 'Bosnian', 'language_code' => 'bs', 'language_name_vi' => 'Tiếng Bosnia'],
            ['language_name' => 'Bulgarian', 'language_code' => 'bg', 'language_name_vi' => 'Tiếng Bulgaria'],
            ['language_name' => 'Catalan', 'language_code' => 'ca', 'language_name_vi' => 'Tiếng Catalan'],
            ['language_name' => 'Cebuano', 'language_code' => 'ceb', 'language_name_vi' => 'Tiếng Cebuano'],
            ['language_name' => 'Chinese (Simplified)', 'language_code' => 'zh', 'language_name_vi' => 'Tiếng Trung Giản Thể'],
            ['language_name' => 'Chinese (Traditional)', 'language_code' => 'zh-TW', 'language_name_vi' => 'Tiếng Trung Phồn Thể'],
            ['language_name' => 'Corsican', 'language_code' => 'co', 'language_name_vi' => 'Tiếng Corse'],
            ['language_name' => 'Croatian', 'language_code' => 'hr', 'language_name_vi' => 'Tiếng Croatia'],
            ['language_name' => 'Czech', 'language_code' => 'cs', 'language_name_vi' => 'Tiếng Séc'],
            ['language_name' => 'Danish', 'language_code' => 'da', 'language_name_vi' => 'Tiếng Đan Mạch'],
            ['language_name' => 'Dutch', 'language_code' => 'nl', 'language_name_vi' => 'Tiếng Hà Lan'],
            ['language_name' => 'English', 'language_code' => 'en', 'language_name_vi' => 'Tiếng Anh'],
            ['language_name' => 'Esperanto', 'language_code' => 'eo', 'language_name_vi' => 'Tiếng Esperanto'],
            ['language_name' => 'Estonian', 'language_code' => 'et', 'language_name_vi' => 'Tiếng Estonia'],
            ['language_name' => 'Finnish', 'language_code' => 'fi', 'language_name_vi' => 'Tiếng Phần Lan'],
            ['language_name' => 'French', 'language_code' => 'fr', 'language_name_vi' => 'Tiếng Pháp'],
            ['language_name' => 'Frisian', 'language_code' => 'fy', 'language_name_vi' => 'Tiếng Frisia'],
            ['language_name' => 'Galician', 'language_code' => 'gl', 'language_name_vi' => 'Tiếng Galicia'],
            ['language_name' => 'Georgian', 'language_code' => 'ka', 'language_name_vi' => 'Tiếng Georgia'],
            ['language_name' => 'German', 'language_code' => 'de', 'language_name_vi' => 'Tiếng Đức'],
            ['language_name' => 'Greek', 'language_code' => 'el', 'language_name_vi' => 'Tiếng Hy Lạp'],
            ['language_name' => 'Gujarati', 'language_code' => 'gu', 'language_name_vi' => 'Tiếng Gujarat'],
            ['language_name' => 'Haitian Creole', 'language_code' => 'ht', 'language_name_vi' => 'Tiếng Haiti'],
            ['language_name' => 'Hausa', 'language_code' => 'ha', 'language_name_vi' => 'Tiếng Hausa'],
            ['language_name' => 'Hawaiian', 'language_code' => 'haw', 'language_name_vi' => 'Tiếng Hawaii'],
            ['language_name' => 'Hebrew', 'language_code' => 'he', 'language_name_vi' => 'Tiếng Do Thái'],
            ['language_name' => 'Hindi', 'language_code' => 'hi', 'language_name_vi' => 'Tiếng Hindi'],
            ['language_name' => 'Hmong', 'language_code' => 'hmn', 'language_name_vi' => 'Tiếng Hmong'],
            ['language_name' => 'Hungarian', 'language_code' => 'hu', 'language_name_vi' => 'Tiếng Hungary'],
            ['language_name' => 'Icelandic', 'language_code' => 'is', 'language_name_vi' => 'Tiếng Iceland'],
            ['language_name' => 'Igbo', 'language_code' => 'ig', 'language_name_vi' => 'Tiếng Igbo'],
            ['language_name' => 'Indonesian', 'language_code' => 'id', 'language_name_vi' => 'Tiếng Indonesia'],
            ['language_name' => 'Irish', 'language_code' => 'ga', 'language_name_vi' => 'Tiếng Ireland'],
            ['language_name' => 'Italian', 'language_code' => 'it', 'language_name_vi' => 'Tiếng Ý'],
            ['language_name' => 'Japanese', 'language_code' => 'ja', 'language_name_vi' => 'Tiếng Nhật'],
            ['language_name' => 'Javanese', 'language_code' => 'jv', 'language_name_vi' => 'Tiếng Java'],
            ['language_name' => 'Kannada', 'language_code' => 'kn', 'language_name_vi' => 'Tiếng Kannada'],
            ['language_name' => 'Kazakh', 'language_code' => 'kk', 'language_name_vi' => 'Tiếng Kazakh'],
            ['language_name' => 'Khmer', 'language_code' => 'km', 'language_name_vi' => 'Tiếng Khmer'],
            ['language_name' => 'Korean', 'language_code' => 'ko', 'language_name_vi' => 'Tiếng Hàn'],
            ['language_name' => 'Kurdish', 'language_code' => 'ku', 'language_name_vi' => 'Tiếng Kurd'],
            ['language_name' => 'Kyrgyz', 'language_code' => 'ky', 'language_name_vi' => 'Tiếng Kyrgyz'],
            ['language_name' => 'Lao', 'language_code' => 'lo', 'language_name_vi' => 'Tiếng Lào'],
            ['language_name' => 'Latin', 'language_code' => 'la', 'language_name_vi' => 'Tiếng Latinh'],
            ['language_name' => 'Latvian', 'language_code' => 'lv', 'language_name_vi' => 'Tiếng Latvia'],
            ['language_name' => 'Lithuanian', 'language_code' => 'lt', 'language_name_vi' => 'Tiếng Litva'],
            ['language_name' => 'Luxembourgish', 'language_code' => 'lb', 'language_name_vi' => 'Tiếng Luxembourg'],
            ['language_name' => 'Macedonian', 'language_code' => 'mk', 'language_name_vi' => 'Tiếng Macedonia'],
            ['language_name' => 'Malagasy', 'language_code' => 'mg', 'language_name_vi' => 'Tiếng Malagasy'],
            ['language_name' => 'Malay', 'language_code' => 'ms', 'language_name_vi' => 'Tiếng Mã Lai'],
            ['language_name' => 'Malayalam', 'language_code' => 'ml', 'language_name_vi' => 'Tiếng Malayalam'],
            ['language_name' => 'Maltese', 'language_code' => 'mt', 'language_name_vi' => 'Tiếng Malta'],
            ['language_name' => 'Maori', 'language_code' => 'mi', 'language_name_vi' => 'Tiếng Maori'],
            ['language_name' => 'Marathi', 'language_code' => 'mr', 'language_name_vi' => 'Tiếng Marathi'],
            ['language_name' => 'Mongolian', 'language_code' => 'mn', 'language_name_vi' => 'Tiếng Mông Cổ'],
            ['language_name' => 'Myanmar (Burmese)', 'language_code' => 'my', 'language_name_vi' => 'Tiếng Miến Điện'],
            ['language_name' => 'Nepali', 'language_code' => 'ne', 'language_name_vi' => 'Tiếng Nepal'],
            ['language_name' => 'Norwegian', 'language_code' => 'no', 'language_name_vi' => 'Tiếng Na Uy'],
            ['language_name' => 'Nyanja (Chichewa)', 'language_code' => 'ny', 'language_name_vi' => 'Tiếng Nyanja'],
            ['language_name' => 'Pashto', 'language_code' => 'ps', 'language_name_vi' => 'Tiếng Pashto'],
            ['language_name' => 'Persian', 'language_code' => 'fa', 'language_name_vi' => 'Tiếng Ba Tư'],
            ['language_name' => 'Polish', 'language_code' => 'pl', 'language_name_vi' => 'Tiếng Ba Lan'],
            ['language_name' => 'Portuguese', 'language_code' => 'pt', 'language_name_vi' => 'Tiếng Bồ Đào Nha'],
            ['language_name' => 'Punjabi', 'language_code' => 'pa', 'language_name_vi' => 'Tiếng Punjabi'],
            ['language_name' => 'Romanian', 'language_code' => 'ro', 'language_name_vi' => 'Tiếng Romania'],
            ['language_name' => 'Russian', 'language_code' => 'ru', 'language_name_vi' => 'Tiếng Nga'],
            ['language_name' => 'Samoan', 'language_code' => 'sm', 'language_name_vi' => 'Tiếng Samoa'],
            ['language_name' => 'Scots Gaelic', 'language_code' => 'gd', 'language_name_vi' => 'Tiếng Gaelic Scotland'],
            ['language_name' => 'Serbian', 'language_code' => 'sr', 'language_name_vi' => 'Tiếng Serbia'],
            ['language_name' => 'Sesotho', 'language_code' => 'st', 'language_name_vi' => 'Tiếng Sesotho'],
            ['language_name' => 'Shona', 'language_code' => 'sn', 'language_name_vi' => 'Tiếng Shona'],
            ['language_name' => 'Sindhi', 'language_code' => 'sd', 'language_name_vi' => 'Tiếng Sindhi'],
            ['language_name' => 'Sinhala', 'language_code' => 'si', 'language_name_vi' => 'Tiếng Sinhala'],
            ['language_name' => 'Slovak', 'language_code' => 'sk', 'language_name_vi' => 'Tiếng Slovak'],
            ['language_name' => 'Slovenian', 'language_code' => 'sl', 'language_name_vi' => 'Tiếng Slovenia'],
            ['language_name' => 'Somali', 'language_code' => 'so', 'language_name_vi' => 'Tiếng Somali'],
            ['language_name' => 'Spanish', 'language_code' => 'es', 'language_name_vi' => 'Tiếng Tây Ban Nha'],
            ['language_name' => 'Sundanese', 'language_code' => 'su', 'language_name_vi' => 'Tiếng Sunda'],
            ['language_name' => 'Swahili', 'language_code' => 'sw', 'language_name_vi' => 'Tiếng Swahili'],
            ['language_name' => 'Swedish', 'language_code' => 'sv', 'language_name_vi' => 'Tiếng Thụy Điển'],
            ['language_name' => 'Tajik', 'language_code' => 'tg', 'language_name_vi' => 'Tiếng Tajik'],
            ['language_name' => 'Tamil', 'language_code' => 'ta', 'language_name_vi' => 'Tiếng Tamil'],
            ['language_name' => 'Telugu', 'language_code' => 'te', 'language_name_vi' => 'Tiếng Telugu'],
            ['language_name' => 'Thai', 'language_code' => 'th', 'language_name_vi' => 'Tiếng Thái'],
            ['language_name' => 'Turkish', 'language_code' => 'tr', 'language_name_vi' => 'Tiếng Thổ Nhĩ Kỳ'],
            ['language_name' => 'Ukrainian', 'language_code' => 'uk', 'language_name_vi' => 'Tiếng Ukraina'],
            ['language_name' => 'Urdu', 'language_code' => 'ur', 'language_name_vi' => 'Tiếng Urdu'],
            ['language_name' => 'Uzbek', 'language_code' => 'uz', 'language_name_vi' => 'Tiếng Uzbekistan'],
            ['language_name' => 'Vietnamese', 'language_code' => 'vi', 'language_name_vi' => 'Tiếng Việt'],
            ['language_name' => 'Welsh', 'language_code' => 'cy', 'language_name_vi' => 'Tiếng Wales'],
            ['language_name' => 'Xhosa', 'language_code' => 'xh', 'language_name_vi' => 'Tiếng Xhosa'],
            ['language_name' => 'Yiddish', 'language_code' => 'yi', 'language_name_vi' => 'Tiếng Yiddish'],
            ['language_name' => 'Yoruba', 'language_code' => 'yo', 'language_name_vi' => 'Tiếng Yoruba'],
            ['language_name' => 'Zulu', 'language_code' => 'zu', 'language_name_vi' => 'Tiếng Zulu'],
        ];


        DB::table('languages')->insert($languages);
    }
}
